openapi: 3.0.0
info:
  title: Appointment API
  description: API para agendamiento de citas por país.
  version: 1.0.0

servers:
  - url: https://{api_id}.execute-api.us-east-1.amazonaws.com/dev
    variables:
      api_id:
        default: your-api-id

paths:
  /appointments:
    post:
      summary: Crear una nueva cita
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                insuredId:
                  type: string
                  example: insured-001
                scheduleId:
                  type: string
                  example: schedule-001
                countryISO:
                  type: string
                  enum: [PE, CL]
                  example: PE
      responses:
        '201':
          description: Cita creada exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Appointment created
                  appointment:
                    $ref: '#/components/schemas/Appointment'
        '400':
          description: Error de validación
        '500':
          description: Error interno del servidor

  /appointments/{insuredId}:
    get:
      summary: Obtener citas por ID de asegurado
      parameters:
        - name: insuredId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Lista de citas encontradas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Appointment'
        '400':
          description: ID de asegurado faltante

components:
  schemas:
    Appointment:
      type: object
      properties:
        id:
          type: string
        insuredId:
          type: string
        scheduleId:
          type: string
        countryISO:
          type: string
        createdAt:
          type: string
        status:
          type: string
          example: pending
